### ISSUE TITLE
How stable is this plugin?

### ISSUE THREAD

**Issue by ken-vernaillen** [fastrde/cordova-plugin-fastrde-mqtt#2]
How stable is this plugin?
How does it compare to other similar plugins? For example [cordova-plugin-mqtt](https://github.com/arcoirislabs/cordova-plugin-mqtt)?
This is the first plugin that seems to support SSL. Are there known bugs?
Is it safe to use in professional environment?

**Comment by fastrde** [comment]
not stable.
cordova-plugin-mqtt for example is android only.
I didn't **know** any ssl bugs but others.
Definitely NOT.

Tests, further development and pullrequests are welcome.

**Comment by ken-vernaillen** [comment]
Thanks for the info!
