### ISSUE TITLE
need help to fix MQTT ios cordova plugin [CONNACK problem]

### ISSUE THREAD

**Issue by abogdanovich** [fastrde/cordova-plugin-fastrde-mqtt#8]
Hi guys!

Firstly, many thanks for your submitted open source code at https://github.com/fastrde. We appreciate your work! Thanks!

We tried to use your code from Github: https://github.com/fastrde/cordova-plugin-fastrde-mqtt and got some troubles.... We found out  that the fix from giriiton solved a part of problems (decencies) > https://github.com/giriiton/cordova-plugin-fastrde-mqtt/blob/master/plugin.xml#L10 but we have a problem connected with "CONNACK" - it seems that the problem began from your source code

"SyntaxError: Unexpected identifier 'CONNACK'. Expected ')' to end an argument list."

Guys, could you please help us! And double check your code (Object C binary) and fix that issue? Or maybe you can show the problem place and we'll fix that.

Had no chance to play with Object C code.... :)

**Comment by fastrde** [comment]
does it only happen on iOS?
Which broker you are connecting to?
Can you show me the important part of your code?

The connection itself is handled by the [MQTTClient.Framework](https://github.com/ckrey/MQTT-Client-Framework) the CONNACK flag should not be propageted to you (nor me).
I use this plugin in a published app for ios and android and published today an updated version to the stores without any MQTT issues.
